---
title: "Seminar2Notes.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup
```{r, eval = FALSE}
install.packages("tidyverse", dependencies = TRUE)
```

## mpg data frame
```{r, eval = FALSE}
head(mpg)
?mpg
```

## Creating a ggplot
```{r}
library(tidyverse)
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, color = class))
```

## New Template
New template
ggplot(data = <DATA>) + 
  <GEOM_FUNCTION>(
     mapping = aes(<MAPPINGS>),
     stat = <STAT>, 
     position = <POSITION>
  ) +
  <COORDINATE_FUNCTION> +
  <SCALE_FUNCTION> +
  <AXIS_FUNCTION> +
  <FACET_FUNCTION>
  
### Smooth line
```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + geom_point() +geom_smooth()
```
 
### Continuous variable as the third dimension
```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = year)) + geom_point() + geom_smooth()
```

## Bar plots
```{r}
averageEfficiency <- mpg %>% group_by(class) %>% summarise(fuel_efficiency = mean(hwy))

# axis label
ggplot(averageEfficiency) + geom_bar(aes(x = class, y = fuel_efficiency, fill = class), stat = "identity") + ylab("Fuel Efficiency (miles per gallon)") + xlab("Vehicle Type")

# scale inversion
ggplot(averageEfficiency) + 
  geom_bar(aes(x = class, y = fuel_efficiency, fill = class),
           stat = "identity") +
  ylab("Fuel Efficiency (miles per gallon)") +
  xlab("Vehicle Type") +
  scale_y_reverse()

# coordination flip
ggplot(averageEfficiency) + 
  geom_bar(aes(x = class, y = fuel_efficiency, fill = class),
           stat = "identity") +
  coord_flip()

# pie chart
ggplot(averageEfficiency) + 
  geom_bar(aes(x = class, y = fuel_efficiency, fill = class),
           stat = "identity") +
  coord_polar()
```

## Mutiple plots
```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + geom_point() + facet_wrap(~class)
```

